
schema_registry:
  path: ./config/schema_registry

data_dictionary:
  path: ./config/data_dictionary.json

canonical_types:
  path: ./config/canonical_types

openai:
  model: gpt-4o-mini
  temperature: 0.5
  max_tokens: 1000

vector_store:
  schema_collection_name: schema_rag
  data_dictionary_collection_name: data_dictionary_rag
  canonical_types_collection_name: canonical_types_rag
  chunk_size: 1000
  chunk_overlap: 200

logging:
  level: INFO
  file: "schema_rag.log"


bigquery:
  sample_data_rows: 1000
  key_path: ./config/keys/service_account.json
  project_id: montgomery-282015
  dataset_id: autolog
